package practice.project.euler.problem.p60_69;

import practice.project.euler.Problem;
import practice.project.euler.util.PolygonUtil;

/*
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

   1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
   2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
   3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

 */
public class Problem61 implements Problem{
    public String getAnswer() throws Exception {



        boolean polyagonals[][][] = new boolean[6][100][100];
        boolean checked[] = new boolean[polyagonals.length];

        for (int p = 0;p<polyagonals.length;p++)
            for (int j = 10;j<100;j++)
                for (int k = 10;k<100;k++)
                    polyagonals[p][j][k] = PolygonUtil.isPolyagonalNumber(p + 3, j * 100 + k);


        for (int i = 10;i<100;i++) {
            long retVal = findCycleSum(i,0,0,checked,polyagonals);
            if (retVal >= 0)
                return Long.toString(retVal);
        }


        return null;
    }

    private static long findCycleSum(int prevVal, int firstVal, int numChecked, boolean checked[], boolean polyagonals[][][]) {

        if (numChecked ==polyagonals.length && prevVal%100 == firstVal/100)
            return 0;

        int baseIdx = prevVal % 100;

        for (int p = 0;p<polyagonals.length;p++)
            if (!checked[p]) {
                checked[p] = true;

                for (int i = 10;i<polyagonals[p][baseIdx].length;i++)
                    if (polyagonals[p][baseIdx][i]) {
                        int currNum = baseIdx * 100 + i;
                        long retVal = findCycleSum(
                                currNum,
                                (firstVal==0?currNum:firstVal),
                                numChecked+1,
                                checked,
                                polyagonals);
                        if (retVal>=0)
                            return currNum + retVal;

                    }

                checked[p] = false;
            }

         return -1;
    }

}
