package practice.project.euler.problem.p01_09;

import practice.project.euler.Problem;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Problem2 implements Problem{
    public String getAnswer() {

        long prev = 1;
        long sum = 2;
        long retVal=sum;

        while (sum < 4000000)
        {
            long tmp = prev;
            prev = sum;
            sum += tmp;
            if (sum%2==0)
                retVal += sum;
        }



        return Long.toString(retVal);
    }
}
