package practice.project.euler.problem;

import practice.project.euler.Problem;
import practice.project.euler.util.PolygonNumUtil;

/*
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

   1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
   2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
   3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

 */
public class Problem61 implements Problem{
    public String getAnswer() throws Exception {

        int maxTriN = (int)(PolygonNumUtil.getPolyagonalN(3,10000));

        for (int triN = (int)(PolygonNumUtil.getPolyagonalN(3,1000)) + 1;triN<=maxTriN;triN++) {
            int triBase = ( (triN * (triN + 1))/2 )%10;
            int maxSquN = (int)(Math.sqrt((triBase + 1) * 100));

            for (int squN = (int)(Math.sqrt(triBase * 100)) + 1; squN < maxSquN;squN++) {
                int squBase = ( squN * squN )%10;
                int maxPenN = (int)(PolygonNumUtil.getPolyagonalN(5,(squBase + 1) * 100)) + 1;

                for (int penN = (int)(PolygonNumUtil.getPolyagonalN(5,squBase * 100)) + 1; penN < maxPenN;penN++) {
                    int penBase = ( (penN * ( 3*penN -1)) / 2 )%10;
                    int maxHexN = 1000;

                    for (int hexN = (int)(PolygonNumUtil.getPolyagonalN(6,penBase * 100)) + 1; hexN < maxHexN;hexN++)


                }



            }

        }

        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }
}
