package practice.project.euler.problem.p40_49;

import practice.project.euler.Problem;

import static practice.project.euler.util.PolygonUtil.genPolyagonalNum;
import static practice.project.euler.util.PolygonUtil.isPolyagonalNumber;

/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

 */
public class Problem44 implements Problem{
    public String getAnswer() throws Exception {

        for (int i = 1;;i++) {
            long currPent = genPolyagonalNum(5, i);
            for (int j = i-1;j>0;j--) {
                long checkPent = genPolyagonalNum(5, j);
                if (isPolyagonalNumber(5, currPent - checkPent) &&
                        isPolyagonalNumber(5, currPent + checkPent))
                    return Long.toString(currPent - checkPent);
            }
        }

    }
}
